// Court Code'un günlük kelime havuzu. "code" boşluksuz, tek parça ve büyük harf olmalı (tahmin edilecek kelime).
// "fullName" sadece kazanınca ekranda gösterilen tam isim.
import { getDailyItem } from './dailyRotation';
 
export const COURT_CODE_POOL = [
  { code: "ALPEREN", fullName: "ALPEREN ŞENGÜN" },
  { code: "LEBRON", fullName: "LEBRON JAMES" },
  { code: "CURRY", fullName: "STEPHEN CURRY" },
  { code: "DURANT", fullName: "KEVIN DURANT" },
  { code: "HARDEN", fullName: "JAMES HARDEN" },
  { code: "GIANNIS", fullName: "GIANNIS ANTETOKOUNMPO" },
  { code: "LUKA", fullName: "LUKA DONCIC" },
  { code: "JOKIC", fullName: "NIKOLA JOKIC" },
  { code: "EMBIID", fullName: "JOEL EMBIID" },
  { code: "TATUM", fullName: "JAYSON TATUM" },
  { code: "MORANT", fullName: "JA MORANT" },
  { code: "BOOKER", fullName: "DEVIN BOOKER" },
  { code: "LILLARD", fullName: "DAMIAN LILLARD" },
  { code: "IRVING", fullName: "KYRIE IRVING" },
  { code: "KOBE", fullName: "KOBE BRYANT" },
  { code: "JORDAN", fullName: "MICHAEL JORDAN" },
  { code: "MAGIC", fullName: "MAGIC JOHNSON" },
  { code: "BIRD", fullName: "LARRY BIRD" },
  { code: "SHAQ", fullName: "SHAQUILLE O'NEAL" },
  { code: "NASH", fullName: "STEVE NASH" },
  { code: "DUNCAN", fullName: "TIM DUNCAN" },
  { code: "NOWITZKI", fullName: "DIRK NOWITZKI" },
  { code: "PIPPEN", fullName: "SCOTTIE PIPPEN" },
  { code: "RODMAN", fullName: "DENNIS RODMAN" },
  { code: "WADE", fullName: "DWYANE WADE" },
  { code: "PARKER", fullName: "TONY PARKER" },
  { code: "GINOBILI", fullName: "MANU GINOBILI" },
  { code: "PAYTON", fullName: "GARY PAYTON" },
  { code: "LEONARD", fullName: "KAWHI LEONARD" },
  { code: "GEORGE", fullName: "PAUL GEORGE" },
  { code: "WESTBROOK", fullName: "RUSSELL WESTBROOK" },
  { code: "HARDAWAY", fullName: "ANFERNEE HARDAWAY" },
  { code: "IVERSON", fullName: "ALLEN IVERSON" },
  { code: "CARTER", fullName: "VINCE CARTER" },
  { code: "GARNETT", fullName: "KEVIN GARNETT" },
  { code: "PIERCE", fullName: "PAUL PIERCE" },
  { code: "ALLEN", fullName: "RAY ALLEN" },
  { code: "STOCKTON", fullName: "JOHN STOCKTON" },
  { code: "MALONE", fullName: "KARL MALONE" },
  { code: "BARKLEY", fullName: "CHARLES BARKLEY" },
  { code: "OLAJUWON", fullName: "HAKEEM OLAJUWON" },
  { code: "ROBINSON", fullName: "DAVID ROBINSON" },
  { code: "MOURNING", fullName: "ALONZO MOURNING" },
  { code: "EWING", fullName: "PATRICK EWING" },
  { code: "DREXLER", fullName: "CLYDE DREXLER" },
  { code: "WILKINS", fullName: "DOMINIQUE WILKINS" },
  { code: "ERVING", fullName: "JULIUS ERVING" },
  { code: "BAYLOR", fullName: "ELGIN BAYLOR" },
  { code: "WEST", fullName: "JERRY WEST" },
  { code: "RUSSELL", fullName: "BILL RUSSELL" },
  { code: "CHAMBERLAIN", fullName: "WILT CHAMBERLAIN" },
  { code: "ABDULJABBAR", fullName: "KAREEM ABDUL-JABBAR" },
  { code: "HAYES", fullName: "ELVIN HAYES" },
  { code: "FRAZIER", fullName: "WALT FRAZIER" },
  { code: "MONROE", fullName: "EARL MONROE" },
  { code: "REED", fullName: "WILLIS REED" },
  { code: "COUSY", fullName: "BOB COUSY" },
  { code: "PETTIT", fullName: "BOB PETTIT" },
  { code: "UNSELD", fullName: "WES UNSELD" },
  { code: "GERVIN", fullName: "GEORGE GERVIN" }
];
 
// Gün başına (UTC gece yarısında değişen) bir kelime — tur bitince sıra karışıp yeniden başlar,
// aynı ay içinde asla tekrar etmez, bir sonraki turda da farklı bir sırayla ilerler.
export const getTodaysCourtCode = () => getDailyItem(COURT_CODE_POOL);